server:
  port: 9001

spring:
  application:
    name: GatewayOWSM

  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**,/api/roles/**

        - id: NewsService
          uri: http://localhost:8082
          predicates:
            - Path=/api/news/**,/api/categories/**,/api/comments/**,/api/Tags/**,/api/authors/**,/api/media-assets/**
      default-filters:
        - DedupedResponseHeader=Access-Control-Allow-Origin RETAIN_UNIQUE